### ISSUE TITLE
Add Footer in the base file

### ISSUE THREAD

**Issue by sruti2024** [sruti2024/PRO_Act#1]
Add a footer with the copyright, contact details  and social media handles . Add this to the base.html file in templates . Needs to be responsive !

**Comment by kunal299** [comment]
@sruti2024 I would contribute to this issue also. Plz assign this issue to me as a part of gssoc'21.

**Comment by sruti2024** [comment]
Surely You can contribute , as told the coding phase will start from 4th march , so you shall e assigned then , till then you can work on this and even go through the other issues!

**Comment by kunal299** [comment]
@sruti2024 The dates are changed and our coding period will start from 8th March.

**Comment by nilisha-jais** [comment]
I want to work on it

**Comment by DhanyaHegde01** [comment]
please, assign this to me. I would like to work on this

**Comment by nandini7637** [comment]
Hello I would like to contribute to it being a part of GSSOC.

**Comment by sruti2024** [comment]
hi  @nandini7637 @DhanyaHegde01 @nilisha-jais , this project is under gssoc21, as instructed that a common channel will be made soon for each project as soon as it is done we can have discussion , I shall try to assign one issue to each to have a good start  and u ppl are also free to frame your own issues , if they are acceptable u will be the first one to be assigned!

**Comment by sahildotexe** [comment]
Hey !! I am a participant of GSSOC'21 , can you assign this issue to me?

**Comment by sruti2024** [comment]
@DhanyaHegde01 assigning you this one create a design first get it approved and then continue with the PR.

**Comment by jankivaghasiya** [comment]
Hello sir,
I would like to contribute to this as a GSSOC'21 participant. Can you please assign me this?

**Comment by DhanyaHegde01** [comment]
Ok..

**Comment by DhanyaHegde01** [comment]
Hey...how do I get my design approved before the pull request?

**Comment by sruti2024** [comment]
communicate the design to me or the mentors on discord (username - Sruti | pro_act |PA )

**Comment by sujoy-coder** [comment]
@sruti2024 I want to work on this issue
I have contributed in this project earlier so I know about the project 
Thank You

**Comment by sruti2024** [comment]
okay @sujoy-coder move ahead with this

**Comment by sujoy-coder** [comment]
what should be the content for footer ? 
Please mention
