### ISSUE TITLE
[GSSOC'21] Toggle Button for Dark and Light mode 

### ISSUE THREAD

**Issue by manastole03** [sruti2024/PRO_Act#10]
Hey, I am Manas Tole a GSSOC'21 Participant.
I want to add a toggle button on each page for Dark and Light mode
This feature is most important to this project as well as  it is convenient to users to use.
Please issue this task to me.
I want to complete this task under your guidance.
Thank-you   :)

@sruti2024

**Comment by sruti2024** [comment]
Great to have this feature in the project , I am assigning you this one , add the toggle button on the nav bar in the base file so that it is automatically implemented in each page , and after designing verify the same either with me or the project  mentor before making a PR!

**Comment by sahilempire** [comment]
Hello @sruti2024 , I want to work on this issue, **Please assign me**.
Maybe the **above assignee unable to solve the issue**, if so please assign me.

Thank you.

**Comment by sahilempire** [comment]
Hello @sruti2024 , I want to work on this issue, **Please assign me**.
Maybe the **above assignee unable to solve the issue**, if so, please assign me.

Thank you.

**Comment by mohammedjameel24** [comment]
Assign me ⚫

**Comment by arpit456jain** [comment]
@PROTechThor I think may be above assignee was unable to solve the issue, Its been 17 days when this issue was assigned to him. Kindly assign it to me I will work on it as soon as possible.

**Comment by arpit456jain** [comment]
@sruti2024 Can you please assign me this I want to try it. I am a gssoc'21 participant

**Comment by sruti2024** [comment]
@manastole03 updates?

**Comment by manastole03** [comment]
Yeah I will create a pull request in few days.

**Comment by mohammedjameel24** [comment]
Assign me

**Comment by arpit456jain** [comment]
@sruti2024 I had already made a toggle a button just have to add it to project.
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/55352601/113770890-571ab000-9740-11eb-9da4-4b38a9c52570.png">
if possible kindly assign it to me I will make a PR in an hour

**Comment by mohammedjameel24** [comment]
> Assign me ⚫

Assign me please

**Comment by sruti2024** [comment]
@manastole03 updates ??

**Comment by arpit456jain** [comment]
@sruti2024 assign me under GSSoC'21

**Comment by sahilempire** [comment]
@sruti2024 I asked you to assign me on this issue before, it's my turn now.
Please Assign me.

Thank you.

**Comment by mohammedjameel24** [comment]
Assign me

**Comment by mohammedjameel24** [comment]
> Assign me ⚫

Please assign me

**Comment by Aditya201551** [comment]
@sruti2024 please assign me the task next if the assignee is unable to complete the task

**Comment by mohammedjameel24** [comment]
> Hello @sruti2024 , I want to work on this issue, **Please assign me**.
> Maybe the **above assignee unable to solve the issue**, if so, please assign me.
> 
> Thank you.

Assign me 
@sruti2024

**Comment by sahilempire** [comment]
@sruti2024 Can you please specify, **which type of toggle button** you want, like it **should be on Nav bar** (top right corner, next to log out) or **a button like 'go to top button'**.

Thank you.

**Comment by Aditya201551** [comment]
@sruti2024 i will start the work by tonight

**Comment by mohammedjameel24** [comment]
I should get assigned !!!@sruti2024

**Comment by Aditya201551** [comment]
@sruti2024 Mam, pr is ready I am pushing the PR
