### ISSUE TITLE
Creating dynamic form for the user in add projects page

### ISSUE THREAD

**Issue by coding-geek21** [sruti2024/PRO_Act#100]
### **Feature request**:
Creating dynamic form in the add projects page will help users to add more links like they can add github link and also some other links like hosted webpage link

I would like to work on this  can you please assign me?

**Comment by SaiSudhaV** [comment]
Nice one @coding-geek21

**Comment by sruti2024** [comment]
@coding-geek21 any updates??

**Comment by coding-geek21** [comment]
> @coding-geek21 any updates??
Yes since i was having exams i was not able to complete, I will complete within 2 or 3 days

**Comment by sruti2024** [comment]
updates??
