### ISSUE TITLE
[Gssoc'21] Enhancing the footer

### ISSUE THREAD

**Issue by arpit456jain** [sruti2024/PRO_Act#101]
### **Feature request**:
I want to improve the current footer, as it is currently very dull and simple.

**Comment by PROTechThor** [comment]
@aditi1403 Please explain in detail the enhancements you want to make

**Comment by arpit456jain** [comment]
@PROTechThor I want to replace it with this.
<img width="960" alt="3" src="https://user-images.githubusercontent.com/55352601/113381120-c2a8fa00-939b-11eb-9c86-66eaf088c131.png">

**Comment by sruti2024** [comment]
will including the about is not really required because there shall be a separate section for that and quick links are present in nav currently but if u want to add any animation in the footer like the double shade wave, etc then that can be done !

**Comment by arpit456jain** [comment]
@sruti2024 What about this footer.

https://user-images.githubusercontent.com/55352601/113518299-18032800-95a3-11eb-94e1-f21e37ee9612.mp4

**Comment by arpit456jain** [comment]
and @sruti2024  kindly assign me issue #104 its s very small issue.

**Comment by sruti2024** [comment]
yes this seems cool , just change the color scheme and it shall be perfect

**Comment by arpit456jain** [comment]
<img width="960" alt="ed" src="https://user-images.githubusercontent.com/55352601/113664468-690d3c00-96c9-11eb-8af2-864df1e083fb.png">

@sruti2024  is it ok ?? if no kindly specify which color do you want. if yes then I will replace the footer in website to this and will create a PR as soon as possible.

**Comment by sruti2024** [comment]
yes color seems to be good , don't replace the footer just attach it with the footer

**Comment by arpit456jain** [comment]
ok @sruti2024 I will add it and make a PR  for this very soon. 
I had already created a PR for bug in front-end kindly review it #111

**Comment by SnehaVeerakumar** [comment]
Please someone resolve this issue and merge it. It is hectic with current footer which overlaps with the contents.

**Comment by arpit456jain** [comment]
> Please someone resolve this issue and merge it. It is hectic with current footer which overlaps with the contents.

@SnehaVeerakumar its because of the fixed bottom property of footer.

**Comment by CMELAKKIA** [comment]
@arpit456jain Yeah I had to find it before adding a field. Thank you😅
