### ISSUE TITLE
Host the website using heroku

### ISSUE THREAD

**Issue by FireQueen-3010** [sruti2024/PRO_Act#103]
### **Feature request**:
The idea is to host the website using heroku so that it is visible to the public.

### **Is your feature request related to a problem? Please describe. (optional)**:
Right now, it is hard to view the website without actually accessing through local host

### **Describe the solution you'd like**:
The website can be deployed using heroku or netlify.

### **Describe how this feature will be useful to our readers**:
The link to the website can also be added to repo so that anyone who visits the repo can easily access the website and also vice versa.

### **Additional context:**

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by FireQueen-3010** [comment]
Please assign me this under gssoc'21

**Comment by sruti2024** [comment]
But the site is not completed yet so any change made needs to be simultaneously exercised on the hosted one as well , so wouldn't it be better if it is hosted once when most of the site is done?

**Comment by FireQueen-3010** [comment]
Okay
