### ISSUE TITLE
[Gssoc'21] Bug in front-end

### ISSUE THREAD

**Issue by arpit456jain** [sruti2024/PRO_Act#104]
### **Describe the bug:**
the footer overlap the techstack and its looks very ugly and annoying
<img width="960" alt="p1" src="https://user-images.githubusercontent.com/55352601/113479553-659d6900-94ad-11eb-9d8a-1a616c9370ed.png">

### **To Reproduce:**
4. See an error

### **Additional context:**

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by arpit456jain** [comment]
@Aditya201551 kindly assign me this issue.

**Comment by arpit456jain** [comment]
@Aditya201551 kindly assign me this issue so I can create a PR

**Comment by Aditya201551** [comment]
> @Aditya201551 kindly assign me this issue so I can create a PR

Please ask pa to assign you this task......I cannot assign you the tasks

**Comment by arpit456jain** [comment]
ok @Aditya201551 . @PROTechThor kindly assign me this issue.

**Comment by SaiSudhaV** [comment]
@arpit456jain I guess similar kind of issue is already resolved previously by @Aditya201551

**Comment by arpit456jain** [comment]
@SaiSudhaV  I don't know @Aditya201551 asked me to reverted the changes that i had done in footer because of which this issue is occurring but reverting css of footer will affect the contact page so I created this issue to fix the overlapping.
If it's already solved @Aditya201551 please let me know

**Comment by Aditya201551** [comment]
@SaiSudhaV yes, ease assign this issue to @arpit456jain he will fix that bug in contact section

**Comment by arpit456jain** [comment]
@SaiSudhaV kindly review my PR.
