### ISSUE TITLE
Adding Space Indentation to PRO_Act/templates/index.html Code.

### ISSUE THREAD

**Issue by Diksha-11** [sruti2024/PRO_Act#110]
I am a gssoc'21 participant and I would like to add space indentation to the .html file that is PRO_Act/templates/index.html, to the code below {% block body %}. 

It is just to increase the readibility of index page. Since html files can be inspect at frontend also, Thus readability is an important aspect that must be considered.

# Prerequisites:
-  I checked to make sure that this issue has not already been filed.
-  I'm reporting the issue to the correct repository (for multi-repository projects) 

# Expected Behavior:
This change will not affect the behaviour of the projrct. It will just increase the readibility of index page. 

# Solution: 
I'll be giving space indentation to PRO_Act/templates/index.html to the code below {% block body %}

Thus, I request  maintainers to please assign me this issue.

**Comment by Diksha-11** [comment]
Please /assign this issue to me

**Comment by sruti2024** [comment]
sorry but adding space , indentation in readme and spell check cannot be considered as issues for marking !
