### ISSUE TITLE
[GSSOC '21] Adding Sub Task Functionality to Manage Projects

### ISSUE THREAD

**Issue by niksm7** [sruti2024/PRO_Act#114]
### **Feature request**:
When we click on the manage project button for any specific project we get a page with some information on the right along with a "Add Subtask" button which just opens up a dialogue box but this box provides no functionality and doesn't add any subtask.

### **Describe the solution you'd like**:
I would like to create model for storing the sub tasks related to each project and also display them accurately under specific projects when the user goes to the manage section of a project.

### **Describe how this feature will be useful to our readers**:
This will help teams in managing the project in a more agile and systematic manner.

### **Additional context:**
I'm GSSOC '21 participant and would like to work on this issue so kindly assign me the same.

**Comment by sruti2024** [comment]
@niksm7 made my work easier ! go on with the issue , hope to see good results !

**Comment by niksm7** [comment]
> @niksm7 made my work easier ! go on with the issue , hope to see good results !

Thank you! Won't disappoint you 😃
