### ISSUE TITLE
Creating the Profile Update page

### ISSUE THREAD

**Issue by somya51p** [sruti2024/PRO_Act#115]
### **Feature request**:
As for now, the profile update page is not synced with the signup details. Users can visit the page and update his or her profile. If he wants to change the username or email, it can be done by this functionality.

### **Is your feature request related to a problem? Please describe. (optional)**:
The profile update button is not active only the username is mentioned in the code.

### **Describe the solution you'd like**:
Creating a complete profile update page with good CSS.

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. 

@sruti2024 I wish to work on the same.Please assign me the same user GSSOC'21.

**Comment by sruti2024** [comment]
could you please elaborate as the functionality was already added as per my knowledge.
