### ISSUE TITLE
Adding image upload option in Add project page

### ISSUE THREAD

**Issue by somya51p** [sruti2024/PRO_Act#116]
### **Feature request**:
Users can upload an image of their project so an image upload functionality should be given.

### **Describe how this feature will be useful to our readers**:
A precise picture of the project can be given if we give the option to upload an image of the same.

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. 

@sruti2024 I wish to work on this issue. Please assign me the same.

**Comment by SaiSudhaV** [comment]
@somya51p Wasn't this issue already there?
I think #6 is an issue similar to this please check it once.

**Comment by somya51p** [comment]
@SaiSudhaV I apologize, I misinterpreted issue number #6 as uploading an image for the user profile.
