### ISSUE TITLE
Discussion panel or chat room for that particular project they are working on.

### ISSUE THREAD

**Issue by giridhar7889** [sruti2024/PRO_Act#118]
### **Feature request**:
A discussion panel is where people contributing to that project may discuss the problems and stuff.

### **Is your feature request related to a problem? Please describe.
Yes, as there is nowhere virtually to chat with the people who are contributing to the project and discuss the tasks and problems they're facing.

### **Describe the solution you'd like**:
I would like to implement the backend part of developing a discussion panel or chat room for that particular project.

### **Describe how this feature will be useful to our readers**:
When people get assigned a task they face a lot of problems, they can use another way of contacting their teammates or if you wanted your users to engage with your application then you should have a chat room or discussion panel to handle that kind of process.

**Comment by giridhar7889** [comment]
@sruti2024 can I work on this issue? , please assign this to me

**Comment by sruti2024** [comment]
but currently it is a individual based project management and not a team based one so how are the ppl supposed to interact?
