### ISSUE TITLE
[GSSOC' 21] [ENHANCEMENT] Re-designing login with google/ button

### ISSUE THREAD

**Issue by Aditya201551** [sruti2024/PRO_Act#120]
# Prerequisites:

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I checked to make sure that this issue has not already been filed.

- [x] I'm reporting the issue to the correct repository (for multi-repository projects) **(optional)**

- Re-designing login with google button and making it more slim and appealing(older one looks kinda ugly)
- Re-positioning it with proper alignment 

# Solution: 

- Adding new button codes

@SaiSudhaV @sruti2024 @chdharm

**Comment by PROTechThor** [comment]
Looks like a valid issue to me. Go ahead, @Aditya201551. Thanks for all your contributions :)

**Comment by Aditya201551** [comment]
> Looks like a valid issue to me. Go ahead, @Aditya201551. Thanks for all your contributions :)

Thank you so much for acknowledging my contributions! :)
