### ISSUE TITLE
Spell check in readme.md

### ISSUE THREAD

**Issue by harinyadevi** [sruti2024/PRO_Act#122]
# Prerequisites:

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I checked to make sure that this issue has not already been filed.

- [x] I'm reporting the issue to the correct repository (for multi-repository projects) **(optional)**

# Expected Behavior:

Spelling checked

# Current Behavior:

Instead of 'particular', it has been typed as 'perticular'

# Solution: 

Replace it with right spelling

# Screenshots (optional):

![image](https://user-images.githubusercontent.com/77061666/113971358-3e9cb980-9856-11eb-84e7-efbe54eeb13d.png)

**Comment by harinyadevi** [comment]
I would like to make a PR for this issue
@sruti2024 
@SaiSudhaV

**Comment by PROTechThor** [comment]
@harinyadevi Go ahead!

**Comment by harinyadevi** [comment]
@PROTechThor I have created a PR for this issue (PR #126 )
