### ISSUE TITLE
Adding WhatsApp click to chat feature

### ISSUE THREAD

**Issue by harinyadevi** [sruti2024/PRO_Act#125]
### **Feature request**:
To add a WhatsApp click to chat button.

### **Describe the solution you'd like**:
I will add a WhatsApp button (bottom right corner in the webpage) which when clicked by the user would allow the user to directly interact with the website administrators.

### **Describe how this feature will be useful to our readers**:
As WhatsApp is the most widely used direct messaging app, it would provide the website visitors to directly communicate with the owners, thus providing faster solutions to their questions/issues.

### **Additional context:**
I would like to work on this feature.

<hr/>

**Comment by sruti2024** [comment]
whose contact shall be shared??

**Comment by harinyadevi** [comment]
Right now, I have just given a random number in the code. When the website gets deployed at a later stage, one of the website administrator's contact shall be shared.
