### ISSUE TITLE
[GENERAL] [GSSOC' 21] Legacy code in login and signup page

### ISSUE THREAD

**Issue by Aditya201551** [sruti2024/PRO_Act#128]
# Prerequisites:

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I checked to make sure that this issue has not already been filed.

- [x] I'm reporting the issue to the correct repository (for multi-repository projects) **(optional)**

# ISSUE

- There is Legacy code(no longer supported code) in the CSS section of the login and signup page as I have designed login with google feature so during initial deployment the code for the button was added and now after redesigning the button the CSS of the previous button is still in the page that would take longer load time as its a CSS code

# Solution: 

- So I would like to fix up this issue in this project

# Video (optional):

https://user-images.githubusercontent.com/32588231/114310471-7763b980-9b08-11eb-9ed1-19f04b82f68b.mp4

@sruti2024 @PROTechThor @SaiSudhaV @chdharm

**Comment by sruti2024** [comment]
okay
