### ISSUE TITLE
[BUG] [Gssoc' 21] Anyone can view projects without logging in to the webapp

### ISSUE THREAD

**Issue by Aditya201551** [sruti2024/PRO_Act#129]
### **Describe the bug:**
- Anyone can view projects of the app directly without logging in to the app if they have the URL of the view, i.e if anyone types `http://127.0.0.1:8000/project_view/` they can view the projects present In the app without logging in

### **To Reproduce:**
- Type `http://127.0.0.1:8000/project_view/` without logging in

### **Expected behavior:**
- Redirection to login page

### **Screenshots:**
NA

### **Additional context:**
I would like to work on this issue please assign me this issue

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

@SaiSudhaV @PROTechThor @sruti2024 @chdharm

**Comment by sruti2024** [comment]
okay since this issue is regularly coming up do a thing fix this bug for all the pages that are currently there , will that be alright?

**Comment by Aditya201551** [comment]
@sruti2024 sure i can do that

**Comment by sruti2024** [comment]
okay
