### ISSUE TITLE
Welcome email on sign up

### ISSUE THREAD

**Issue by sruti2024** [sruti2024/PRO_Act#130]
### **Feature request**:
As soon as a user sign up to the site an welcome email should be sent to the registered mail ID along with details about the pro_act and contact details , create html template and verify before coding the same.

### **Describe the solution you'd like**:
A standard email to be generate as soon as a user signs up .

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by SalmaFarghaly** [comment]
Hello @sruti2024 I would like to work on this issue can you assign it to me ?
