### ISSUE TITLE
Option to add profile picture in the profile page , also display the same on the page 

### ISSUE THREAD

**Issue by sruti2024** [sruti2024/PRO_Act#131]
### **Feature request**:
option to add profile picture in the profile section , also the same must be displayed and also an option to update the picture should be provided.

### **Is your feature request related to a problem? Please describe. (optional)**:
the profile section seems to be a bit empty

### **Additional context:**
add a working video of the same along with the PR .

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by arpit456jain** [comment]
@sruti2024 i would like to give it a Try

**Comment by arpit456jain** [comment]
@sruti2024 I am not able to solve this issue you can assign it to someone else

**Comment by Aryamanz29** [comment]
I would like to work on this issue , Could you please assign to me

**Comment by sruti2024** [comment]
updates?

**Comment by Aryamanz29** [comment]
> updates?

Yes , Now my exams are over & I'm completing pending issues one by one and raising PR's asap ✌️.

**Comment by Aryamanz29** [comment]
> > updates?
> 
> Sorry for thr delay,  Now my exams are over & I'm completing pending issues one by one and raising PR's asap ✌️.

**Comment by Aryamanz29** [comment]
@sruti2024  Please review PR
