### ISSUE TITLE
Enhancement in social media icons 

### ISSUE THREAD

**Issue by arpit456jain** [sruti2024/PRO_Act#136]
### **Feature request**:
Cool and attractive social media icons in footer.

### **Is your feature request related to a problem? Please describe. (optional)**:
Social media icons are very dull and static

### **Describe the solution you'd like**:
I would like to make social media icons more attractive and want to add animation to it

### **Describe how this feature will be useful to our readers**:
A clear and concise description of how this feature will be useful for our  other readers.

### **Additional context:**

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by saumyaparikh** [comment]
I would like to work as a GSSOC participant.
I will use font awesome for social media icon.
when the mouse pointer will hover on the icon it will show the full name with colour transition

**Comment by arpit456jain** [comment]
> I would like to work as a GSSOC participant.
> I will use font awesome for social media icon.
> when the mouse pointer will hover on the icon it will show the full name with colour transition

 @saumyaparikh  i had already made these icons 
<img width="286" alt="icons" src="https://user-images.githubusercontent.com/55352601/114814598-1838ca00-9dd2-11eb-94e5-938f16699285.png">

for the website just have to add animation .
waiting for confirmation from @sruti2024 @SaiSudhaV  kindly assign me this

**Comment by saumyaparikh** [comment]
> > I would like to work as a GSSOC participant.
> > I will use font awesome for social media icon.
> > when the mouse pointer will hover on the icon it will show the full name with colour transition
> 
> @saumyaparikh i had already made these icons
> <img alt="icons" width="286" src="https://user-images.githubusercontent.com/55352601/114814598-1838ca00-9dd2-11eb-94e5-938f16699285.png">
> 
> for the website just have to add animation .
> waiting for confirmation from @sruti2024 @SaiSudhaV kindly assign me this

Okay🙌

**Comment by SaiSudhaV** [comment]
@saumyaparikh Thanks for showing interest if you feel something can be added to this project you can create an issue on yourself, that can be assigned to you.

**Comment by arpit456jain** [comment]
@SaiSudhaV kindly add the label of gssoc

And one more thing project is using pandas but its not mention in requirements.txt kindly look into it, i can add it to file just need the version details which will be compatible

**Comment by arpit456jain** [comment]
@SaiSudhaV @sruti2024 kindly review my PR and add suitable labels to it
