### ISSUE TITLE
Confirmation Alert before Logout

### ISSUE THREAD

**Issue by arpit456jain** [sruti2024/PRO_Act#147]
Confirmation Alert before Logout like this.
<img width="361" alt="sweet alert" src="https://user-images.githubusercontent.com/55352601/115538795-e0da8980-a2b9-11eb-948c-cdcbcd566af8.png">

**Comment by PROTechThor** [comment]
This seems like a valid feature to me. Carry on :)

**Comment by arpit456jain** [comment]
Kindly add label of level

**Comment by sruti2024** [comment]
@arpit456jain do keep the display on a model , small and simple
