### ISSUE TITLE
Create a route for displaying User Profile

### ISSUE THREAD

**Issue by sujoy-coder** [sruti2024/PRO_Act#15]
Hi @sruti2024 , I would like to work on this issue as a participant of GSSoC'21. Here I am thinking to create css card view for the user profile which contains Information of the user.

please assign it to me 🙏

**Comment by sruti2024** [comment]
Great idea , have a profile tab on the nav to lead to the profile page try keeping the color scheme same and first design it and get it approved by either  me or the mentors then can start with the coding part !

**Comment by sujoy-coder** [comment]
Yes of course.... I am started working on it
Thank You 😇

**Comment by sruti2024** [comment]
Please see through the comments on your PR

**Comment by sujoy-coder** [comment]
I am not able to understand. Though I made changes in my PR. Could you be more specific what I need to do now ?
@sruti2024
