### ISSUE TITLE
Adding A Preloader

### ISSUE THREAD

**Issue by VaibhavSharma24** [sruti2024/PRO_Act#156]
**Feature request**:
I would love to add a Preloader to the site to make it look more good and nice so whenever someone refreshes the page it will appear.

**Note:**
I would love to add this feature

**Comment by VaibhavSharma24** [comment]
@sruti2024 In which file should i add the Preloader !

**Comment by VaibhavSharma24** [comment]
@sruti2024 Please review this preloader and if you want any changes to be made then please let me know.

https://user-images.githubusercontent.com/72144747/116424188-ee19ea00-a85e-11eb-843f-34c997371111.mp4

**Comment by VaibhavSharma24** [comment]
@sruti2024 Please check this one is it looking fine or should i change it more ?

https://user-images.githubusercontent.com/72144747/116811851-0e042300-ab69-11eb-95fd-9a315e1336c0.mp4

**Comment by sruti2024** [comment]
yeah the design seems fine just attach a video showing the full process i.e. signup --> loading --> home page

**Comment by Aryamanz29** [comment]
@VaibhavSharma24 Any updates?😅

**Comment by VaibhavSharma24** [comment]
> @Aryamanz29  Any updates?😅

I am for the delay actually my laptop had some problem so thats why i didnt got the chance to update you ! 
 
All things are ready i just have to add this preloader to every page.
