### ISSUE TITLE
Bug : Adding multiple project with same name

### ISSUE THREAD

**Issue by Aryamanz29** [sruti2024/PRO_Act#158]
### **Describe the bug:**
Adding multiple projects with the same name causes `MultipleObjectsReturned` error 

#### **See this 👇**

![Screenshot (79)](https://user-images.githubusercontent.com/56113566/115920283-9a428600-a497-11eb-8bc6-ac14546d432e.png)

![same_project](https://user-images.githubusercontent.com/56113566/115919919-1ab4b700-a497-11eb-9db2-c4587e67a24c.gif)

### **Expected behavior:**
- Add project form must have constraints for adding new projects ie. it should alert that  **_"Project with same name already exists!!!"_**

<hr/>

**Comment by Aryamanz29** [comment]
I'll start working on this issue from 1st of may because right now my exams are going on.@SaiSudhaV

**Comment by SaiSudhaV** [comment]
@Aryamanz29 Any updates?

**Comment by Aryamanz29** [comment]
> @Aryamanz29 Any updates?
> 

I'll raise PR tomorrow

**Comment by Aryamanz29** [comment]
@SaiSudhaV @sruti2024  Need your review for this 👉 #196
