### ISSUE TITLE
Create requirements.txt file

### ISSUE THREAD

**Issue by ksh168** [sruti2024/PRO_Act#16]
requirements.txt is missing. Adding it will help new contributors to install all dependencies directly. 
**What is requirements.txt?**
See [here](https://www.idkrtm.com/what-is-the-python-requirements-txt/)

I would like to work on this issue in GSSoC'21. Please assign this to me.
Thanks!

**Comment by sruti2024** [comment]
Sure , can work on it !

**Comment by ksh168** [comment]
Hi! I have made the PR.
