### ISSUE TITLE
DOCS : Missing commit guildelines in `contributing.md`

### ISSUE THREAD

**Issue by Aryamanz29** [sruti2024/PRO_Act#161]
- After seeing many PR in this repo I found that contributors don't follow the proper` commit message style`.
-  Proper commit messages help project maintainers and new contributors to helps them to understand project source code more easily
-  Also contibuting. md missing conventional  commit guidelines
-  There is no link in  `README.md` that redirects new contributors to `contributing.md `
- For ref : [Conventional Commit Guidelines](https://www.conventionalcommits.org/en/v1.0.0/)

**Comment by PROTechThor** [comment]
Hi. I'm not sure if this is really necessary for now. Commit guidelines are usually relevant for large projects or projects with automatically-generated changelogs. Not sure if we need it, or if anyone will bother to follow it. 

I'll let another mentor step in and share their thoughts on this issue
