### ISSUE TITLE
Rename : `kebab-case` filename to `snake_case`

### ISSUE THREAD

**Issue by Aryamanz29** [sruti2024/PRO_Act#165]
- Some files in ` ./templates , ./static/js` have different naming convention.
- Rename those files to follow the single `snake_case` naming convention.
-  Also search for the `kebab-case` notation in source code if found then rename it as well.
-  Note: Do changes in the codebase as well if they link into the project.
### **Some SS below 👇:**

![Screenshot (87)](https://user-images.githubusercontent.com/56113566/115933045-bfd98a80-a4ab-11eb-85a2-7020e8096334.png)
![Screenshot (88)](https://user-images.githubusercontent.com/56113566/115933047-c10ab780-a4ab-11eb-967c-30cfc088b276.png)

**Comment by Srishti013** [comment]
Hi,
I am a GSSOC'21 participant and I would like to work on this issue please assign it to me @Aryamanz29

**Comment by Aryamanz29** [comment]
@sruti2024  Review this issue please and assign it to 😉 @Srishti013

**Comment by Aryamanz29** [comment]
> Hi,
> I am a GSSOC'21 participant and I would like to work on this issue please assign it to me @Aryamanz29

@Srishti013  Any updates?
