### ISSUE TITLE
Bug : SignUp through signup_form fails

### ISSUE THREAD

**Issue by Aryamanz29** [sruti2024/PRO_Act#167]
### **Describe the bug:**

 SignUp through signup_form throws an `error while sending OTP, try again`

### **To Reproduce 👇 :**

![registration_bug](https://user-images.githubusercontent.com/56113566/115953756-de22a300-a50a-11eb-95ed-60d00890c033.gif)

### **Expected behavior:**
It should successfully register a new user.

**Comment by arpit456jain** [comment]
I don't understand what's the need of sending otp in signing up . I

**Comment by Aryamanz29** [comment]
> I don't understand what's the need of sending otp in signing up . I 

Yea I have same doubt , @sruti2024  please clarify this 😅
