### ISSUE TITLE
Move : Internal & Inline CSS to external CSS 

### ISSUE THREAD

**Issue by Aryamanz29** [sruti2024/PRO_Act#168]
### Description :
- I found templates having inline and internal CSS which is indigestible to new contributors.

![Screenshot (91)](https://user-images.githubusercontent.com/56113566/115954331-05c73a80-a50e-11eb-97f7-0491f3f41082.png)

![Screenshot (92)](https://user-images.githubusercontent.com/56113566/115954333-06f86780-a50e-11eb-8891-4c96efd6b1bf.png)

### Expected : 

- Remove all inline and internal CSS to external CSS and place them into the ` ./static/` directory also do necessary changes to the project codebase to work the same as before.

**Comment by PROTechThor** [comment]
Nice catch! This is a minor but relevant issue :)

**Comment by Aryamanz29** [comment]
@sruti2024 @SaiSudhaV @PROTechThor  Need Review for this PR 📝
