### ISSUE TITLE
Clean : Remove redundant comments  

### ISSUE THREAD

**Issue by Aryamanz29** [sruti2024/PRO_Act#169]
- Remove `redundant comments` from project code.

### **See this 👇:**

![Screenshot (98)](https://user-images.githubusercontent.com/56113566/115954668-cf8aba80-a50f-11eb-9602-2ffe7b0a1162.png)

![Screenshot (96)](https://user-images.githubusercontent.com/56113566/115954653-b4b84600-a50f-11eb-8d70-60f2ce2a5cfc.png)

![Screenshot (97)](https://user-images.githubusercontent.com/56113566/115954651-b3871900-a50f-11eb-8ce6-e402420f1d87.png)

**Comment by mukeshmjn** [comment]
Please assign this to me I will remove reduntant code/comments

**Comment by SaiSudhaV** [comment]
@Aryamanz29 any updates?

**Comment by Aryamanz29** [comment]
@SaiSudhaV  I'll Raise PR today ✌️
