### ISSUE TITLE
OTP Verification for Forgot Password

### ISSUE THREAD

**Issue by ashutoshkrris** [sruti2024/PRO_Act#17]
I would like to implement this for Forgot Password Page. I'll be using AJAX requests to enhance user experience/
I am a GSSOC participant, please assign it to me.

**Comment by sruti2024** [comment]
Great ! go on !

**Comment by ashutoshkrris** [comment]
Hey @sruti2024 
I have implemented Forgot password. Could you please verify if everything is okay with it? I have attached the demo for your reference.

https://user-images.githubusercontent.com/47353498/110741080-17a09700-825a-11eb-8d21-798dc12e32f0.mp4

**Comment by sruti2024** [comment]
Great work , send the PR!

**Comment by ashutoshkrris** [comment]
Done @sruti2024
