### ISSUE TITLE
Rename : Variable/Function names 

### ISSUE THREAD

**Issue by Aryamanz29** [sruti2024/PRO_Act#170]
**A good variable name should:**
```
Be clear and concise.
Be written in English. ...
Not contain special characters. ...
Not conflict with any Python keywords, such as for, True, False, and, if, or else .
```
- Different or Bad variables creates problem in debugging and it should be avoided.
-  Rename `variable, functions, etc` name in project `source code`
-  They should `follow` a similar variable naming convention throughout the project. ref  https://www.theserverside.com/definition/Snake-case

### SS below 👇:
- **Existing code** 

![Screenshot (100)_LI](https://user-images.githubusercontent.com/56113566/115955595-18913d80-a515-11eb-9fc5-048c8c5f20bd.jpg)

![Screenshot (101)_LI](https://user-images.githubusercontent.com/56113566/115955596-1a5b0100-a515-11eb-9111-017b6438bf1d.jpg)

![Screenshot (102)_LI](https://user-images.githubusercontent.com/56113566/115955598-1b8c2e00-a515-11eb-9bea-9266efd57b56.jpg)

**Comment by PROTechThor** [comment]
Hi Aryamaz29. Thanks for pointing this out. I agree. 

I believe we should document a set of coding style guidelines, reminding people to follow certain conventions when naming variables and functions. Something like [this](https://github.com/PROTechThor/MISP/blob/contribute/CODINGSTYLE.md). Do you mind creating a new documentation issue to track this?

**Comment by Furquan712** [comment]
I would like to work on this , Will you assignee me

**Comment by Aryamanz29** [comment]
> Hi Aryamaz29. Thanks for pointing this out. I agree. 
> 
> I believe we should document a set of coding style guidelines, reminding people to follow certain conventions when naming variables and functions. Something like [this](https://github.com/PROTechThor/MISP/blob/contribute/CODINGSTYLE.md). Do you mind creating a new documentation issue to track this?

Sure, I'm agree with you. I'll create a new issue for that .
