### ISSUE TITLE
bug in front-end

### ISSUE THREAD

**Issue by arpit456jain** [sruti2024/PRO_Act#172]
### **Describe the bug:**

<img width="960" alt="prob2" src="https://user-images.githubusercontent.com/55352601/116081338-c6d4e880-a6b7-11eb-8a3d-e92203d4f0c0.png">
<img width="960" alt="prob1" src="https://user-images.githubusercontent.com/55352601/116081349-c9cfd900-a6b7-11eb-95db-f12aa62b7c97.png">

**Comment by Aryamanz29** [comment]
I want to know that google auth is working? because after  merging of this PR #152 I'm unable to register as a new user😅

**Comment by arpit456jain** [comment]
> I want to know that google auth is working? because after merging of this PR #152 I'm unable to register as a new user😅

Nope @Aryamanz29  it's not working i am unable to access home page that's why i created super user and login with that creditendials but still not able to access home page 😅😅

**Comment by Aryamanz29** [comment]
@arpit456jain 

> > I want to know that google auth is working? because after merging of this PR #152 I'm unable to register as a new user😅
> 
> Nope @Aryamanz29 it's not working i am unable to access home page that's why i created super user and login with that creditendials but still not able to access home page 😅😅

This is because he removes `db.sqlite3` file in order to resolve the merge conflict from the root which creates a problem now 🤔.

**Comment by arpit456jain** [comment]
yeah may be
