### ISSUE TITLE
UI of view Projects

### ISSUE THREAD

**Issue by arpit456jain** [sruti2024/PRO_Act#180]
I would like to give it a try to make ui of view projects  better.

**Note : The image is not saving in db so i can't render it on view project page . it will show image not found or i can hard code the image part** 

I can make a better ui for The data currently on that page using bootstrap cards 
It will look something like this.
<img width="198" alt="ui of cards" src="https://user-images.githubusercontent.com/55352601/116673575-2f2a0f80-a9c1-11eb-8803-2d363d702825.png">

**Comment by sruti2024** [comment]
can u add something to it for enhancing the ui?

**Comment by arpit456jain** [comment]
> can u add something to it for enhancing the ui?

I can try

**Comment by sruti2024** [comment]
okay then starting designing and verify it , according to the design the level tag shall be given

**Comment by arpit456jain** [comment]
Ok assign me this issue

**Comment by arpit456jain** [comment]
@SaiSudhaV @sruti2024 please merge this PR i had made changes 3rd time
