### ISSUE TITLE
Update README.md 

### ISSUE THREAD

**Issue by KajalSinghBAGHEL** [sruti2024/PRO_Act#184]
remove grammatical mistakes

**Comment by KajalSinghBAGHEL** [comment]
I am a GSSOC participant. Can I work on this issue

**Comment by sruti2024** [comment]
you may check the comments in ur PR

**Comment by PROTechThor** [comment]
@sruti2024 We aren't supposed to accept basic issues like this, right? Or it this issue valid?

**Comment by pranita736** [comment]
I want to work on this issue. Please assign this to me under GSSOC21

**Comment by sruti2024** [comment]
@PROTechThor  yes grammatical and spelling corrections will not be eligible for marking.
