### ISSUE TITLE
Readme file enhancement

### ISSUE THREAD

**Issue by anirudhsai20** [sruti2024/PRO_Act#185]
The Readme file can be enhanced by adding a list of all the Open Source progarms in which this project was listed in.

**Comment by anirudhsai20** [comment]
Hi! Please assign this issue to me under GSSOC.

**Comment by sruti2024** [comment]
I don't really want this to be there in read.me , any other suggestions u can share

**Comment by PROTechThor** [comment]
Not really an enhancement to me. I don't see how this will add any value. Please, come up with a better issue. I'll reopen if you have a better idea.
