### ISSUE TITLE
[GSSOC'21] Custom User model to supoort multiple roles and A profile Model linked to store basic user information.

### ISSUE THREAD

**Issue by nikfzy** [sruti2024/PRO_Act#19]
I would like to Override the default user model used here so that we can introduce custom roles for user and other user level functionalities as per this application need.

**Comment by sruti2024** [comment]
Could you brief me about what all roles you are planning of and how you want to implant they .

**Comment by nikfzy** [comment]
The roles can be anything as of now we can introduce the team member func added by a project admin or something like that i mean higher to lower level user mapping func. The PA can divide the task between its TM's.
