### ISSUE TITLE
Enhancement of CSS of project add page

### ISSUE THREAD

**Issue by sruti2024** [sruti2024/PRO_Act#2]
Improvise the UI UX of the project add page , try using external css/JS only to keep the code clean .

**Comment by kunal299** [comment]
@sruti2024 Could you plz assign this issue to me as a part of Gssoc'21?

**Comment by sruti2024** [comment]
As soon as the coding phase starts  you shall be assigned, till then you can go through the other issues even rise issues of your own!

**Comment by kunal299** [comment]
> As soon as the coding phase starts  you shall be assigned, till then you can go through the other issues even rise issues of your own!

Ok 😊

**Comment by sahildotexe** [comment]
Hey !! I am a participant of GSSOC'21 , can you assign this issue to me?

**Comment by subhangi2731** [comment]
please assign me this

**Comment by kalpanapurohit** [comment]
I would like to work on this issue as a GSSOC'21 participant.

**Comment by sruti2024** [comment]
@kunal299 assigning you with this one, first decide a perfect color palette with the existing shade and also more , verify with me or the mentors and then start designing , also share the images once after it is designed  !

**Comment by sruti2024** [comment]
@kunal299 updates?

**Comment by Upasana1216** [comment]
I want to contribute to this issue. Please assign this to me under GSSOC

**Comment by vismitap** [comment]
May I work on this as a part of GSSoC'21?

**Comment by sruti2024** [comment]
okay assigning both , @Upasana1216 and @vismitap , first do the designing and get it verified by the mentors then move towards the coding part! whose ever design stands out the best , the PR will be merged for them

**Comment by vismitap** [comment]
@sruti2024 Please review. 

 Old SS :  
 ![image](https://user-images.githubusercontent.com/47056243/112421394-f1e4b900-8d54-11eb-94f7-db4d941c4e2c.png) 
New SS
![image](https://user-images.githubusercontent.com/47056243/112421466-1476d200-8d55-11eb-8634-b10c5d754e93.png) 

Changes made: 
* Added box-shadow to navbar
* Fixed the margin issues in navbar and all form elements and now they do not appear to stick to each other.
* Added a card and put the form inside card
* Added box-shadow to card as well
* Changed the title and button color also.

**Comment by sruti2024** [comment]
I quiet liked the whole thing , it would be great if u could experiment with the background color a bit and send me some ss on discord , so that i could select whether this white is good or any other will serve better , also make the labels bold , and chhose technical stack to grey rather than green also widen it like the rest of the inputs !!

**Comment by SaiSudhaV** [comment]
@Upasana1216 any updates?

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by somya51p** [comment]
@SaiSudhaV @sruti2024 If there are no updates in the PR as such, could I take up this issue and work on the same.
