### ISSUE TITLE
Improve the Navbar design

### ISSUE THREAD

**Issue by sruti2024** [sruti2024/PRO_Act#21]
Currently we have a very basic navbar so improve the design of the navbar  keeping the content same .

**Comment by Vijay-Git03** [comment]
I am GSSOC'21 participant and I wan to contribute on this issue,please assign this issue to me! @sruti2024

**Comment by sruti2024** [comment]
sure , go on but first design it out and verify with me then move towards the coding part .

**Comment by simranbhalla3** [comment]
Hi i am gssoc participant and I can improve the navbar using css,js . Please assign this issue to me. @sruti2024

**Comment by sruti2024** [comment]
@simranbhalla3 go on with this issue first create a design get it approved and them move with the coding part

**Comment by sruti2024** [comment]
@simranbhalla3 updates??

**Comment by simranbhalla3** [comment]
> @simranbhalla3 updates??

Working on it , will give you the design asap

**Comment by simranbhalla3** [comment]
@sruti2024 Here's the design . If you like it let me know or i can do further changes
![rescue1](https://user-images.githubusercontent.com/73423545/111867735-ee8baf00-899b-11eb-9e8e-24c00569143e.gif)

**Comment by Sanjana-03** [comment]
![Capture](https://user-images.githubusercontent.com/66235278/112020523-6bfb1f00-8b56-11eb-8e8c-19d47bce6a1e.PNG)

**Comment by simranbhalla3** [comment]
@sruti2024 Please let me know about the design so that i can start working on the issue

**Comment by sruti2024** [comment]
@simranbhalla3 , I really liked the design but wish the color to remain black or 0b3e33 will be fine rest is cool , start with your code

**Comment by sruti2024** [comment]
@simranbhalla3 also there are many changes that have been added recently  so as soon as the code is ready fork the latest one and push all the changes

**Comment by sruti2024** [comment]
@Sanjana-03 I think it hardly has any changes , just a shift form left to right

**Comment by Sanjana-03** [comment]
Yes I know @simrabhalla3 is doing nice work so I am not working on this.

**Comment by simranbhalla3** [comment]
![image](https://user-images.githubusercontent.com/73423545/112593509-9d613c80-8e2d-11eb-8765-d014238f15c7.png)
 
 What design should be of the LogOut button? Same as other options or simple buttons?

**Comment by sruti2024** [comment]
@simranbhalla3 yep this design is perfect !! go on with your PR !

**Comment by sruti2024** [comment]
@simranbhalla3 any update??

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by sruti2024** [comment]
@srishtij2000 sure

**Comment by sruti2024** [comment]
@srishtij2000 updates??

**Comment by SalmaFarghaly** [comment]
Hello @sruti2024 Can I work on this issue ? I will implement the design that simranbhalla3 has mentioned.

**Comment by somya51p** [comment]
@sruti2024 If this issue is yet opened to work on. Please assign me the same, I wish to contribute to it.

**Comment by sruti2024** [comment]
@SalmaFarghaly sure go ahead!!
