### ISSUE TITLE
[GSSOC'21] Master Task and Slave Task func.

### ISSUE THREAD

**Issue by nikfzy** [sruti2024/PRO_Act#22]
Creating a Task Model which can be connected to mutiple slave tasks, which will be in actual sub - tasks of that root task. I will be using 
Modified Pre-order Tree Transversal modeling technique to make tree structure of the relational mapping.

**Comment by sruti2024** [comment]
okay I am assigning you this on , just once you have designed pls verify it with me or the mentors on discord or any other means then move on with the PR

**Comment by nikfzy** [comment]
One More question what are the metrics we people are considering for calculating efficiency of completion of tasks..

**Comment by sruti2024** [comment]
could you be more specific
