### ISSUE TITLE
design a logo for pro_act

### ISSUE THREAD

**Issue by sruti2024** [sruti2024/PRO_Act#23]
Design a logo justifying the purpose of proact and also matching the color scheme . color scheme : https://colorhunt.co/palette/269111

**Comment by RaveenaBhasin** [comment]
I would like to work on this issue.

**Comment by Priyanka7011** [comment]
Hiii I am a GSSOC 2021 participant.
I would also love to design a logo for pro_act.
If you like it, you can make it your official logo .
Please give me one chance.
Thank You !!

**Comment by preetiahuja18** [comment]
Can I fix this issue? @sruti2024 .Please consider this issue to me :)

**Comment by SpecTEviL** [comment]
I would love to work on this if you assign it to me @sruti2024 under GSSoC'21.
Thanks!

**Comment by Tannusharma28** [comment]
> Design a logo justifying the purpose of proact and also matching the color scheme . color scheme : https://colorhunt.co/palette/269111

@sruti2024 Please consider me for this issue. I have learned designing and I'm a GSSOC'21 participant.

**Comment by RaveenaBhasin** [comment]
@sruti2024 I have made a PR for the issue. Please have a look at it

**Comment by RaveenaBhasin** [comment]
I have updated the logo.Please have a look at it.

**Comment by Tannusharma28** [comment]
> Design a logo justifying the purpose of proact and also matching the color scheme . color scheme : https://colorhunt.co/palette/269111

![pro_act logo](https://user-images.githubusercontent.com/65345284/110898888-19d02780-8326-11eb-9369-e14bbc936638.jpeg)


@sruti2024 How about this?
Please assign this issue to me.

**Comment by sruti2024** [comment]
@Priyanka7011 @SpecTEviL @preetiahuja18 @Tannusharma28 , this issue is still open so do a thing design your logos and send them to me on discord , (Username - Sruti | pro_act | PA) , need a compact logo that can be put up on the nav bar as well , follow the color scheme https://colorhunt.co/palette/269111 .one with the best logo will be assigned this issue and obviously your PR will get merged.
@Tannusharma28 great design but need a compact one !

**Comment by Pranjal-2001** [comment]
Could I also give it a try?

**Comment by sruti2024** [comment]
Sure Pranjal go on!

**Comment by dsg1320** [comment]
I would also love to give it a try as part of the GSSOC'21

**Comment by raveena69** [comment]
I would love to work on this  issue

**Comment by raveena69** [comment]
![PRO_ACT](https://user-images.githubusercontent.com/58651579/111078988-012a6200-851e-11eb-8dd8-f79ff2cc7141.png)

I just made a sample logo. How is it? Should I change color or design?

**Comment by ritesh1731** [comment]
I would like to contribute to this issue under GSSOC21. I can make a logo can I try?

**Comment by Upasana1216** [comment]
I would like to contribute to this issue under GSSOC21. I'm have already created many logos for different organizations. I can make a logo can I try?

**Comment by sruti2024** [comment]
@ritesh1731 @Upasana1216 since the PR for this issue is not yet merged so u ppl can give a try !!maintain the purpose of the logo and also the color scheme
