### ISSUE TITLE
add contributing.md

### ISSUE THREAD

**Issue by khareyash05** [sruti2024/PRO_Act#27]
Hi! I would like to add contributing.md to the repo which states on how to clone and fork the repo,how to add ,create and push a repo,squash commits,rebase your feature branch ,how to update forked repo as well as local repo to the changes made in upstream.
I would like to work on this under GSSOC'21.

**Comment by sruti2024** [comment]
cool , but just name the file as something else like guidelines or something else because there is a contributors.md so might get confused , and there is a basic guide in the readme file so add a link there to like for better idea on how to contribute click here !
