### ISSUE TITLE
Create a Contact Us page

### ISSUE THREAD

**Issue by somya51p** [sruti2024/PRO_Act#29]
Hey, @sruti2024. A page from where users could contact the admins if they face any issue, and also contact us, about us and other pages should be available on the home page itself. It looks admirable.
I wish to contribute to this issue under GSSOC'21. Please assign me the same.

**Comment by simranbhalla3** [comment]
Hii , i am a gssoc'21 participant. I would like to create the contact us page for this project, also i have prior knowledge and will complete the work in minimum time. please assign this to me @somya51p @PROTechThor @ksh168

**Comment by sruti2024** [comment]
@somya51p since you have raised the issue to assigning you for contact us page , first design and get approved on discord then go for the coding part.

**Comment by garvitraj** [comment]
@sruti2024 I had experience in front-end and Adobe Xd Pls assign this issue to me i will start with the design if approved then will move to coding part.

**Comment by somya51p** [comment]
@sruti2024, surely I will start today. Can you please provide me the discord server link?

**Comment by somya51p** [comment]
![Capture](https://user-images.githubusercontent.com/64978837/110964300-e5e60980-8307-11eb-899b-e1c771589354.PNG)

@sruti2024 Have a look, recommend the desired changes, and also provide me with the discord server link of this project, it would become easy for me to clear things.

**Comment by sruti2024** [comment]
@somya51p server link : https://discord.com/channels/811724426965811210/815039772874637332

**Comment by Sameek18** [comment]
Hi , i am a gssoc'21 participant. i have prior knowledge of django on designing the frontend as well . Could you please assign this issue to me?

**Comment by Sanjana-03** [comment]
Hi , I am a gssoc'21 participant. Could you please assign this issue to me?
