### ISSUE TITLE
Change the technical stack type from text to multi select

### ISSUE THREAD

**Issue by sruti2024** [sruti2024/PRO_Act#3]
In the project add page change the technical stack selection from plain text to multi selector , also implement changes in the backend.

**Comment by promaroy** [comment]
Can I take up this issue as part of GSSOC'21?

**Comment by promaroy** [comment]
Can I work on this issue as a part of GSSOC '21?

**Comment by sruti2024** [comment]
Yes am assigning you this one , before making the PR share a video of the working either with me or the project mentors for confirmation , make changes in both front and back end , you can also communicate with me on discord username - sruti2024

**Comment by promaroy** [comment]
Ok. Thankyou.

**Comment by promaroy** [comment]
Video (multi select checkbox added)

https://user-images.githubusercontent.com/46682347/110908784-4e97ab00-8335-11eb-948f-d01f3acc75c4.mp4

**Comment by promaroy** [comment]
Shall I make a PR?

**Comment by sruti2024** [comment]
@promaroy  great job , would be better if this can be in a dropdown format and also display the tech stack on the project view page , for any other query communicate on discord

**Comment by promaroy** [comment]
I have made the changes- added dropdown multiselect and listed tech stack in project view page

https://user-images.githubusercontent.com/46682347/111020836-9f1f0f00-83ee-11eb-8c9d-8899d03fe97d.mp4

**Comment by promaroy** [comment]
Shall I proceed to make a PR now?
