### ISSUE TITLE
Login Required

### ISSUE THREAD

**Issue by deeppatel23** [sruti2024/PRO_Act#36]
Will like to make login required to make login compulsory before opening the home page. I would like to work as a part of GSSoC'21.

**Comment by sruti2024** [comment]
I think this feature is already there!

**Comment by deeppatel23** [comment]
@login_required(login_url='/login')
I guess that this code must be added before project_add and project_view functions in views.py to make sure login is required before moving to other pages.

**Comment by deeppatel23** [comment]
It's better to add this after the signup page is complete.

**Comment by PROTechThor** [comment]
@sruti2024 Is this issue relevant or should it be closed?
