### ISSUE TITLE
design a loader

### ISSUE THREAD

**Issue by sruti2024** [sruti2024/PRO_Act#43]
design a loader to be displayed on loading of  the index and other pages after sign up

**Comment by sahilempire** [comment]
hello @sruti2024 I want to work on this issue, **Please assign me**.

Thanking you

**Comment by sruti2024** [comment]
@sahilempire go on with it!

**Comment by sahilempire** [comment]
@sruti2024 Can you please **add** the **level. tag** too.
Thank you

**Comment by garvitraj** [comment]
@sruti2024 can i work on this issue pls assign this to me

**Comment by garvitraj** [comment]
@sruti2024 i too want to contribute on this issue i have graphic designing , ui/ux skills i and make it on XD

**Comment by sruti2024** [comment]
@garvitraj assigning u this one!

**Comment by garvitraj** [comment]
@sruti2024 thanx for assigning this issue to me will surely give a great design by tomorrow

**Comment by garvitraj** [comment]
@sruti2024 i hade designed a loader attaching the xd file below.
and will design one more by today so that i will be sharing in evening

https://user-images.githubusercontent.com/62978449/111864747-cd6d9300-8988-11eb-88bc-804b240199eb.mp4

**Comment by garvitraj** [comment]
is there any update on the loader design 
i have made a new design following the colour as provided in readme should i make a pr??

**Comment by sruti2024** [comment]
go on with the PR but make sure to attach a video that shows the page loading after the loader functionality!

**Comment by garvitraj** [comment]
ok sure
