### ISSUE TITLE
Create a modules page 

### ISSUE THREAD

**Issue by sruti2024** [sruti2024/PRO_Act#5]
There is a button for details at the end of each card in the project view page , on clicking  the  button it should redirect to the modules page which would contain the project details on top  along with a '+' to add modules or sub tasks and their status (completed /ongoing/pending). Followed by a list of sub tasks with their status.

**Comment by nandini7637** [comment]
Hello I would like to contribute to it being a part of GSSOC.

**Comment by subhangi2731** [comment]
can you please assign me this?

**Comment by kalpanapurohit** [comment]
I would like to work on this issue as a GSSOC'21 participant.

**Comment by sruti2024** [comment]
@subhangi2731 updates?

**Comment by sruti2024** [comment]
@kalpanapurohit , assigning you this issue , hope you will be actively doing it !
