### ISSUE TITLE
Adding google captcha on login page.

### ISSUE THREAD

**Issue by 2001asjad** [sruti2024/PRO_Act#50]
I would like to add "I am not a robot captcha" on the login page and signup pages as well,
Can you please assign it to me.
I am a GSSOC 21 participant.
Thank You

**Comment by sruti2024** [comment]
surely u can but currently we have only the login page the signup page is being worked out so  , you first work on the login page as soon as the sign up page is ready work on that as well , will that be fine?

**Comment by 2001asjad** [comment]
@sruti2024  more than fine. I am on it
