### ISSUE TITLE
add footer in web page

### ISSUE THREAD

**Issue by sujoy-coder** [sruti2024/PRO_Act#51]
Hi @sruti2024  , I want to add a footer inside all necessary webpage .
I am a participant @ GSSOC21

Please assign it to me 🙏

Thank You...

**Comment by sruti2024** [comment]
we already have a issue for footer but it seems to have no progress so its would be better if u comment there then the issue can be passed on if its not worked out

**Comment by sujoy-coder** [comment]
Oo

**Comment by sujoy-coder** [comment]
I have closed this issue Now... 😊
