### ISSUE TITLE
updating requirements.txt

### ISSUE THREAD

**Issue by sujoy-coder** [sruti2024/PRO_Act#54]
### The Errors are Showing : 
- ModuleNotFoundError: No module named 'crispy_forms'
- ModuleNotFoundError: No module named 'PIL'

I want to fix this bugs

**Comment by sruti2024** [comment]
@sujoy-coder go on

**Comment by sujoy-coder** [comment]
This issue can be resolved by #55 PR which was already made by myself.
Please Check it 
Thank You
