### ISSUE TITLE
[FEATURE] [GSSOC' 21] Adding google authentication for login

### ISSUE THREAD

**Issue by Aditya201551** [sruti2024/PRO_Act#58]
@sruti2024 

-> Using google API for allowing the user to login and logout through google and adding remember me feature

![google-ss](https://user-images.githubusercontent.com/32588231/111175692-aef54980-85ce-11eb-9e60-4dcb535cc362.png)

ThankYou!(GSSOC' 21 participant)

**Comment by sruti2024** [comment]
yup go on !!

**Comment by Aditya201551** [comment]
please add gssoc' 21 tag as it helps while scoring

**Comment by PROTechThor** [comment]
Merged! Thanks, @Aditya201551
