### ISSUE TITLE
Option to add image 

### ISSUE THREAD

**Issue by sruti2024** [sruti2024/PRO_Act#6]
While entering details of project there must be an option to upload image related to the project .

**Comment by kunal299** [comment]
@sruti2024 I would also contribute to this issue. Plz assign me this issue as a part of gssoc'21.

**Comment by sahildotexe** [comment]
Hey !! I am a participant of GSSOC'21 , can you assign this issue to me?

**Comment by manastole03** [comment]
Hey, please assign this work to me I am having experience in UI / UX developement.
Intrested to solve this issue.
Thank-you

**Comment by sruti2024** [comment]
@kunal299 since you already have been assigned a issue , I shall pass it on to @sahildotexe , do verify by taking a video before making a pr fg the working 
@manastole03 there is an immense need for improvisation of ui/ux in this project so opt for the once related to them or even create some of your own !

**Comment by sahildotexe** [comment]
@sruti2024 I have few doubts, how can we connect ?

**Comment by sahildotexe** [comment]
I have added the upload image option. Please refer to the video link I have given below and let me know if I can make PR.
Link : https://drive.google.com/file/d/1BmOmgylQbMUoTNh9pvNZcL0dI6Qn5nvE/view?usp=sharing

**Comment by sruti2024** [comment]
@sahildotexe the video was not really clear to me , you can make the pr so that i can check ur codes

**Comment by 2001asjad** [comment]
@sruti2024 I want to give it a go.. Can you assign this to me??

**Comment by Sameek18** [comment]
@sruti2024  Can you please assign this issue to me?

**Comment by sruti2024** [comment]
@Sameek18 go on !

**Comment by sruti2024** [comment]
Please attach a video showing the required functionality along with ur PR!

**Comment by Sameek18** [comment]
> Please attach a video showing the required functionality along with ur PR!

okay.

**Comment by sruti2024** [comment]
@Sameek18 updates??

**Comment by SnehaVeerakumar** [comment]
I would like to work on this issue as a part of GSSOC'21. As I already have source code for this issue,  I can complete it as soon as possible. Maximum of 1 day is required for me to complete this issue. @sruti2024

**Comment by SnehaVeerakumar** [comment]
I have added demo video. Source code is ready for this issue. If the current assignee crosses the deadline, kindly assign me to make a PR. 

DEMO VIDEO : https://drive.google.com/file/d/1gxgNxY_y2TGv-LJiNAsmgR3nC7aB9bz1/view?usp=sharing

**Comment by SaiSudhaV** [comment]
@2001asjad updates please?

**Comment by SaiSudhaV** [comment]
Great work!!! @SnehaVeerakumar

**Comment by sruti2024** [comment]
@SnehaVeerakumar updates??

**Comment by 2001asjad** [comment]
> @SnehaVeerakumar updates??

Please assign this one to the next participant.

**Comment by SnehaVeerakumar** [comment]
> @SnehaVeerakumar updates??

@sruti2024  I am getting an small error and contacting mentors regarding this. Kindly give me 2 days to complete this.

**Comment by SnehaVeerakumar** [comment]
I have added an image field successfully and also admin can add the pictures but the project structure is different, so I have asked an mentor about adding the path. Once the path for image field is added, my work will be done.

**Comment by SnehaVeerakumar** [comment]
I will make a PR by tomorrow @sruti2024 Please don't unassign me before that !!!
