### ISSUE TITLE
[ENHANCEMENT] [GSSOC' 21] Labelling every check box in the project

### ISSUE THREAD

**Issue by Aditya201551** [sruti2024/PRO_Act#62]
I have noticed that on clicking the labels beside the checkbox, it does not get selected or deselected. So, I would like to add this enhancement that on clicking the label, the checkbox gets selected/deselected. 

![Screenshot (43)](https://user-images.githubusercontent.com/32588231/111345125-fcdb8180-86a2-11eb-8ba5-2caa30b70915.png)

for example on clicking "Remember Me" the checkbox beside it gets selected

@sruti2024 please assign me this issue to work on 

ThankYou!

**Comment by PROTechThor** [comment]
@Aditya201551 

Great idea! Go ahead and fix this :)
