### ISSUE TITLE
[Need] Workflow for GSSOC21 issue label

### ISSUE THREAD

**Issue by Aryamanz29** [sruti2024/PRO_Act#67]
I want to add workflow which automatically adds `GSSOC21` label to new issues if they have  labels-synonyms: `'{"GSSOC21":["GSSOC","GSSOC21","gssoc","Gssoc","GSSoC"]}'`  in their `issue body`

![Screenshot from 2021-03-17 15-52-45](https://user-images.githubusercontent.com/56113566/111453959-209dd680-873a-11eb-93ca-37161f201192.png)

**Comment by Aryamanz29** [comment]
I would like to work on this issue

**Comment by PROTechThor** [comment]
Hey @sruti2024. Thoughts on this issue? Is this something we need?

**Comment by sruti2024** [comment]
@Aryamanz29 would u explain how this is going to work because we cannot blindly label all the issue without reviewing them!
