### ISSUE TITLE
Updation in requirements.txt

### ISSUE THREAD

**Issue by kanishka8276** [sruti2024/PRO_Act#68]
django-allauth should be added in requirements.txt
#GsSOC'21

**Comment by PROTechThor** [comment]
Hi @kanishka8276 

Sorry, but I don't understand exactly what this issue is talking about. Please add a detailed explanation of the problem and the solution that should be implemented. 

Thanks!

**Comment by kanishka8276** [comment]
> Hi @kanishka8276
> 
> Sorry, but I don't understand exactly what this issue is talking about. Please add a detailed explanation of the problem and the solution that should be implemented.
> 
> Thanks!

Actually when I installed the requirements for this project and ran it then it showed the error no module named allauth , then I had to install it separately so instead it would be better if we keep it in requirements.txt.

**Comment by PROTechThor** [comment]
@kanishka8276 Okay. Thanks for clarifying. 

@sruti2024 What do you think?

**Comment by sruti2024** [comment]
@kanishka8276 this is a pretty minor but important bug u want to fix but would u do some additional changes as well so that we can give it a level label that would justify it !

**Comment by kanishka8276** [comment]
Well I haven't found any other issue to work on in this project. So Keep this issue for just fixing the bug, not as a part of gssoc21

**Comment by kanishka8276** [comment]
> @kanishka8276 this is a pretty minor but important bug u want to fix but would u do some additional changes as well so that we can give it a level label that would justify it !

Well I haven't found any other issue to work on in this project. So Keep this issue just for improving the project, not as a part of gssoc21
