### ISSUE TITLE
Improvise the ReadMe file

### ISSUE THREAD

**Issue by sruti2024** [sruti2024/PRO_Act#7]
Add more creative stuff to the readme file to make it more attractive !

**Comment by RaveenaBhasin** [comment]
I would like to work on this issue. 
Please assign me this

**Comment by sruti2024** [comment]
This project is under gssoc'21 so issues will be assigned on 4th march when the coding phase starts.

**Comment by RaveenaBhasin** [comment]
Okay...

**Comment by PROTechThor** [comment]
@RaveenaBhasin

Hi. We'll have to discuss exactly what you want to add to the ReadMe first, before you begin writing. This way, you don't spend time writing documentation that is not necessary :)

**Comment by rohank2502** [comment]
Yes Please tell what exactly we have to add so it will be easy to add the given content !! I will like to work with this community

**Comment by RaveenaBhasin** [comment]
@PROTechThor One thing we can do to make the readme look attractive is telling about the project admin and displaying the contributors list

**Comment by PROTechThor** [comment]
> displaying the contributors list

@RaveenaBhasin I like this idea! I think the Readme can have a link to the contributors list, but the actual list should be on a separate page, just to keep things organized. If @prakharshreyash15 and @sruti2024 think this is a good idea, then we may want to create a brand new issue to track this.

**Comment by PROTechThor** [comment]
> Yes Please tell what exactly we have to add so it will be easy to add the given content !! I will like to work with this community

@rohank2502 
I _think_ the Readme has all the basic things a Readme file can have. Right now, we're just looking for creative ideas on what else can be added. Feel free to get creative. Compare our Readme file to that of other projects and tell us if there's anything missing. Also, are there any spelling or grammatical errors? Try building the app locally to see if the instructions are missing any steps?

**Comment by rohank2502** [comment]
> 
> 
> > Yes Please tell what exactly we have to add so it will be easy to add the given content !! I will like to work with this community
> 
> @rohank2502
> I _think_ the Readme has all the basic things a Readme file can have. Right now, we're just looking for creative ideas on what else can be added. Feel free to get creative. Compare our Readme file to that of other projects and tell us if there's anything missing. Also, are there any spelling or grammatical errors? Try building the app locally to see if the instructions are missing any steps?

Ya Sure

**Comment by PROTechThor** [comment]
@rohank2502 @RaveenaBhasin 

Another thing you can do is improve the structure of the Readme file. For example, the "[Getting Started](https://github.com/sruti2024/PRO_Act#getting-started)" section can be renamed to something like "Building the app from source", the steps should be a numbered list, and the instructions should be precise. Use this for inspiration: https://github.com/PROTechThor/misp-website/blob/27786aab420bbd595761116e3d3bf82185f4ffc1/README.md

**Comment by rohank2502** [comment]
> 
> 
> @rohank2502 @RaveenaBhasin
> 
> Another thing you can do is improve the structure of the Readme file. For example, the "[Getting Started](https://github.com/sruti2024/PRO_Act#getting-started)" section can be renamed to something like "Building the app from source", the steps should be a numbered list, and the instructions should be precise. Use this for inspiration: https://github.com/PROTechThor/misp-website/blob/27786aab420bbd595761116e3d3bf82185f4ffc1/README.md

Ok means you want to say that i should modify the wording and make it more attractive or easy to understand !! Actually i am new so need guidance

**Comment by PROTechThor** [comment]
> Ok means you want to say that i should modify the wording and make it more attractive or easy to understand !! 

@rohank2502 That's part of it. There's room for improvements with the overall file structure as well. Be careful though; don't accidentally make the instructions more complicated just because you want to change the wording :) 

The way I see it, this issue is broad and we can have multiple PRs for it :)

**Comment by rohank2502** [comment]
> 
> 
> > Ok means you want to say that i should modify the wording and make it more attractive or easy to understand !!
> 
> @rohank2502 That's part of it. There's room for improvements with the overall file structure as well. Be careful though; don't accidentally make the instructions more complicated just because you want to change the wording :)
> 
> The way I see it, this issue is broad and we can have multiple PRs for it :)

Yes sure I will try my best to modify the read me file and if i think this change will be ok then i will raise a issue will it be ok ? And will that issue will be assigned to me ?

**Comment by PROTechThor** [comment]
> Yes sure I will try my best to modify the read me file and if i think this change will be ok then i will raise a issue will it be ok ? And will that issue will be assigned to me ?

Sounds good :)

**Comment by RaveenaBhasin** [comment]
Other than changing the wording we could change the indentation of the paragraph and images of contributors in the contributors list.
is this issue assigned to me?

**Comment by rohank2502** [comment]
thanks @sruti2024 I will start working on this and will take guidance from you and @PROTechThor time to time This is my first issue assigned so please excuse me if made any mistake !!

**Comment by RaveenaBhasin** [comment]
Thank you @sruti2024 I'll be working on the contributors.md file and since it is my first issue I'll be greatfull if you excuse me for mistakes.
Is there any discord channel on which I can ask my doubts regarding this?

**Comment by rohank2502** [comment]
> 
> 
> Thank you @sruti2024 I'll be working on the contributors.md file and since it is my first issue I'll be greatfull if you excuse me for mistakes.
> Is there any discord channel on which I can ask my doubts regarding this?

@sruti2024  actually we need something like discord or slack !!

**Comment by rohank2502** [comment]
> 
> 
> Thank you @sruti2024 I'll be working on the contributors.md file and since it is my first issue I'll be greatfull if you excuse me for mistakes.
> Is there any discord channel on which I can ask my doubts regarding this?

I will like to suggest you @RaveenaBhasin  not only names but also their profile picture can be included in square shape icons it will look something attractive

**Comment by sruti2024** [comment]
This is a part of gssoc21 and there is already a discord for the same , I hope you both are in there and if not please contact with the organizers

**Comment by RaveenaBhasin** [comment]
Thanks @rohank2502 for the amazing suggestion I was going to implement the same idea

**Comment by rohank2502** [comment]
> 
> 
> Thanks @rohank2502 for the amazing suggestion I was going to implement the same idea

Best luck !!

**Comment by rohank2502** [comment]
> 
> 
> This is a part of gssoc21 and there is already a discord for the same , I hope you both are in there and if not please contact with the organizers

Yes I am there !!

**Comment by RaveenaBhasin** [comment]
@sruti2024 Yes there is a discord channel of GSSOC but I think we need separate project servers so that work goes smoothly

**Comment by PROTechThor** [comment]
> I should think something which we can add in readme file so that it can be easy for new users to get familiar with project and i have to make changes in file readme.md only an 

@rohank2502 Yup :)

If you are making unrelated changes, then submit several PRs so that they will be easy to review. For example, if you want to add a new section and also want to edit spelling/grammatical errors, then submit separate PRs for them. Hope this makes sense?

**Comment by rohank2502** [comment]
@PROTechThor  Need help in making the project on my machine can we get connected on any platform linkedin twitter discord

**Comment by PROTechThor** [comment]
> @PROTechThor Need help in making the project on my machine can we get connected on any platform linkedin twitter discord

@rohank2502 
There's a PRO_Act discord channel. You may ask questions there. https://discord.com/channels/811724426965811210/815039772874637332

**Comment by rohank2502** [comment]
> 
> 
> > @PROTechThor Need help in making the project on my machine can we get connected on any platform linkedin twitter discord
> 
> @rohank2502
> There's a PRO_Act discord channel. You may ask questions there. https://discord.com/channels/811724426965811210/815039772874637332

Ook thanks

**Comment by rohank2502** [comment]
> 
> 
> > @PROTechThor Need help in making the project on my machine can we get connected on any platform linkedin twitter discord
> 
> @rohank2502
> There's a PRO_Act discord channel. You may ask questions there. https://discord.com/channels/811724426965811210/815039772874637332

This link is expired

**Comment by PROTechThor** [comment]
@rohank2502 I see you talking in the #general channel. Can you just scroll down the list of channels and find PRO_Act?

**Comment by rohank2502** [comment]
No @PROTechThor  Mentor are given acess not  participant

**Comment by PROTechThor** [comment]
@rohank2502 Hmm. Not sure what else I can do about it ¯\_(ツ)_/¯

**Comment by rohank2502** [comment]
> 
> 
> @rohank2502 Hmm. Not sure what else I can do about it ¯_(ツ)_/¯

are you on twitter or linkedin ? @PROTechThor

**Comment by PROTechThor** [comment]
> are you on twitter or linkedin ? @PROTechThor

LinkedIn, yes. Twitter, no. Lemme PM you on discord. I have exams this week, so I can't help until next week. But I'll message you just so you know my username :)

**Comment by rohank2502** [comment]
> 
> 
> > are you on twitter or linkedin ? @PROTechThor
> 
> LinkedIn, yes. Twitter, no. Lemme PM you on discord. I have exams this week, so I can't help until next week. But I'll message you just so you know my username :)

Thanks

**Comment by rohank2502** [comment]
No issues Let's do from next week 👍🏻

**Comment by sruti2024** [comment]
@RaveenaBhasin cool if no one else is opting , you can working from next week

**Comment by RaveenaBhasin** [comment]
I have sent a pull request. Please have a look at it

**Comment by somya51p** [comment]
Hey@sruti2024! Many important commands are missing like creating a virtual environment and creating a superuser. I wish to contribute to the same under GSSOC'21. If this issue is not assigned, I would love to work on the same.

**Comment by rohank2502** [comment]
Sorry me & @RaveenaBhasin  are working on this issue !! @somya51p
