### ISSUE TITLE
Enhance the CSS of the Index Page 

### ISSUE THREAD

**Issue by sruti2024** [sruti2024/PRO_Act#70]
### **Feature request**:
Enhance the UI/UX  of the index page , can have some graphs showing the no of projects created , latest project created etc.

### **Is your feature request related to a problem? Please describe. (optional)**:
The problem is that the interface is very simple and needs enhancement

### **Describe the solution you'd like**:
Animations , pictures any enhancement that will improve the view keeping the same color scheme will do great !

### **Describe how this feature will be useful to our readers**:
An interesting index page will attract more people!
<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. 
* First create the design get it verified by the mentors and then move on with the coding also while making the pr attach a ss or video along with it !

**Comment by SalmaFarghaly** [comment]
Hello @sruti2024  I am a GSSoC'21 participant and I would like to work on this issue, Could you assign this issue to me ?

**Comment by SalmaFarghaly** [comment]
Hello @sruti2024 I need to ask you some questions ,There is a p tag in  index.html that has "Add projects -- divide into modules -- update the works done -- set a time limit" So, Should these options direct to any page ? and Should I stick to the chosen colors on this page ?

**Comment by sruti2024** [comment]
currently the add project page is there and rest pages are being worked upon but the line was written to just brief about the work flow , and do slick to the color scheme given

**Comment by SalmaFarghaly** [comment]
Okay, Great !
Can you explain more about the kind of graphs you want on this page ?

**Comment by sruti2024** [comment]
a monthly count graph of the numbers of projects that have been created , further can be divided in graphs showing the completed tasks , pending and ongoing tasks , but the latter is not required for now just for an idea and for any more details contact on discord!

**Comment by sruti2024** [comment]
@SalmaFarghaly updates?

**Comment by SalmaFarghaly** [comment]
@sruti2024 I have lost part of the code that I have written, So I will rewrite it and try to finish the rest of the task as soon as possible, Sorry for any Inconvenience.

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by SalmaFarghaly** [comment]
I am about to finish, I am just drawing final styling.
