### ISSUE TITLE
Adding a to do list.

### ISSUE THREAD

**Issue by kanishka8276** [sruti2024/PRO_Act#72]
### **Feature request**:

Adding a to do list to the home page in which user can add his tasks, mark them done when he has completed it.
 

### **Describe how this feature will be useful to our readers**:

This feature will be Very helpful as this project works on divide and conquer strategy so a to do list is the best way of dividing our work into smaller task and completing them , and this to do list will help us keeping track of our work.

#GSSOC21
Please assign this to me.

**Comment by PROTechThor** [comment]
Hi @sruti2024. Do you think we need this feature? I'm not sure

**Comment by sruti2024** [comment]
@kanishka8276 sorry but don't really need such a feature
