### ISSUE TITLE
Adding an 'other' option in tech stack of project_add.html

### ISSUE THREAD

**Issue by kanishka8276** [sruti2024/PRO_Act#75]
### **Feature request**:
Adding a 'other' option in tech stack drop down and then displaying a text box in which user can enter the tech stack which is not listed in the drop down.
### **Is your feature request related to a problem? Please describe. (optional)**:

Some of the tech stacks are not listed in the drop down and it's not possible to include all the tech stacks in the list.

### **Describe how this feature will be useful to our readers**:

It will be helpful for the users as they might be using a tech stack which is not in the list.

**Comment by sruti2024** [comment]
@kanishka8276  I have created a similar issue #76 so have a check!

**Comment by kanishka8276** [comment]
> @kanishka8276 I have created a similar issue #76 so have a check!

I didn't understand what you are trying to say in that.
