### ISSUE TITLE
Create a loop to generate options in tech stack

### ISSUE THREAD

**Issue by sruti2024** [sruti2024/PRO_Act#76]
### **Describe the bug:**
there are separate lines used to generate each option in the tech stack list this makes the code too long and editing tough , so would be better to have a loop to generate the tech stack in the dropdown list.

### **To Reproduce:**
1. Go to 'project_add file'
2. Scroll down to 'tech _stack'

### **Expected behavior:**
expect to have the same output in the front end stuff , changes to be made in the back end , also add more options along with an 'other' option 

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by Aditya201551** [comment]
I can work on this issue, please assign me

ThankYou(GSSOC' 21 participant)

**Comment by kanishka8276** [comment]
> ### **Describe the bug:**
> there are separate lines used to generate each option in the tech stack list this makes the code too long and editing tough , so would be better to have a loop to generate the tech stack in the dropdown list.
> 
> ### **To Reproduce:**
> Steps to reproduce the behavior:
> 
> 1. Go to 'project_add file'
> 2. Scroll down to 'tech _stack'
> 
> ### **Expected behavior:**
> expect to have the same output in the front end stuff , changes to be made in the back end , also add more options along with an 'other' option
> 
> **Note:**
> 
> * If you want to work on an issue, you should check if it has already been assigned to anyone.
Do you mean that we should create an array with all tech stack and then loop through that array and using javascript property innerHTML get the similar output.

**Comment by sruti2024** [comment]
yes absolutely!!

**Comment by kanishka8276** [comment]
Please assign this to me.

**Comment by kanishka8276** [comment]
> yes absolutely!!

@sruti2024  I would like to contribute to this issue. Please assign this to me.

**Comment by Aditya201551** [comment]
@sruti2024 I would like to do this task with optimized code in Django and the page will be pre-rendered in the backend, please assign me this task

Thank You(GSSOC' 21 participant)

**Comment by Aditya201551** [comment]
I have added Pull Request #81

**Comment by kanishka8276** [comment]
@chdharm  @sruti2024  Sorry, but you should assign an issue on the basis of first come first serve and I was the one who opened similar issue.
