### ISSUE TITLE
Create an about page 

### ISSUE THREAD

**Issue by sruti2024** [sruti2024/PRO_Act#8]
Details will be provided , need to design an about section to contain more details about PRO_act

**Comment by kunal299** [comment]
@sruti2024 I would love to contribute to this issue. Could you plz assign this to me as a part of Gssoc'21?

**Comment by nilisha-jais** [comment]
I want to work on it

**Comment by kunal299** [comment]
@nilisha-jais I am working on it.

**Comment by nandini7637** [comment]
I would like to work on this issue please assign it to me. I am a gssoc participant

**Comment by PROTechThor** [comment]
@kunal299 @nandini7637 @nilisha-jais 

The first step is to design a mockup of the page, using a UI tool like Figma, or any tool of your choice. All of you can independently create UI designs and share themhere. It'll be nice to have several designs to choose from. Once the UI mockup is reviewed and approved, one of you can then start coding.

@sruti2024 Sounds good?

**Comment by sruti2024** [comment]
@PROTechThor  absolutely !!

**Comment by rohank2502** [comment]
I will like to work on this issue !!

**Comment by sruti2024** [comment]
@kunal299 @nilisha-jais @rohank2502  I am assigning all three for this one , as told by @PROTechThor first design a layout and get if verified , one wit the best overall feature will be merged first , if we find any addition feature in the rest of the files they shall also be merged later and you will get marks for them !

**Comment by nandini7637** [comment]
@sruti2024 I have made a sample nav bar, header, footer and little content in between how can I show you this much? 
Is there any discord grp?

**Comment by nandini7637** [comment]
Also @sruti2024  if you want something specific to be added in content section pls specify I'll add it.

**Comment by iharshal0808** [comment]
hello @sruti2024 ma'am 
I have enhanced some styling of about page using css effects.  
    1. I have fixed the navigation bar
    2. Changed the background
    3. Changed the font-styling
    4. Lastly enhanced the buttons
How can I show you???

**Comment by iharshal0808** [comment]
https://github.com/iharshal0808/new-repo/compare/main?expand=1
you can see the required changes here

**Comment by iharshal0808** [comment]
@sruti2024 Kindly let me know What is your organisation name so that I can apply to it pls.....

**Comment by Dhriti-Roy** [comment]
I am a Gssoc'21 participant , I would like to work on it . Kindly assigned it to me.

**Comment by Sanjana-03** [comment]
Hi @sruti2024 I had made changes in about page can you review it and tell me the changes

![image](https://user-images.githubusercontent.com/66235278/111917103-2ed65480-8aa4-11eb-81de-9102f53f5254.png)

**Comment by Abhishekkr93** [comment]
I would like to contribute as a Gssoc21 participant. could you please assign me this?

**Comment by sruti2024** [comment]
@iharshal0808 please attach an ss

**Comment by iharshal0808** [comment]
@sruti2024 ma'am this is the video link
https://user-images.githubusercontent.com/69026742/112636727-7b82ac80-8e63-11eb-862b-a7f4aa343d1c.mp4

and the ss :-
![1st](https://user-images.githubusercontent.com/69026742/112637685-6ce8c500-8e64-11eb-98a1-21e7171715e6.png)
![2nd](https://user-images.githubusercontent.com/69026742/112637727-770ac380-8e64-11eb-91bc-2217bbd14d20.png)
![3rd](https://user-images.githubusercontent.com/69026742/112637734-7a05b400-8e64-11eb-9572-d6819733c318.png)

**Comment by sruti2024** [comment]
okay some changes required :
1. add some padding to the whole block 
2. The center alignment of the key feature is not up to mark make it left align or use a carousal
3. stick to the color scheme given in readme
4. the yellow footer section is not needed , the project already has one so let that be there 
5. use two separate div for the upper description and the key feature part , each key feature can be adjusted in separate divs along with a  catchy picture symbolizing the feature (for reference check out - https://moz.com/about )


and next tym attach a complete video stating with the sign up !
Thank You for your efforts hope to see the best results !

**Comment by sruti2024** [comment]
@iharshal0808 updates?

**Comment by iharshal0808** [comment]
Sorry @sruti2024 ma'am I am unable to complete this task as I am not keeping well.
Sorry to inform you lately but I could not complete it further because of my health.

**Comment by sonaliBedade** [comment]
ma'am I would like to work on this issue. Can you please assign it to me?

**Comment by CMELAKKIA** [comment]
@sruti2024  I can create create the page using the above given design using html CSS. Could you assign this to me?

**Comment by sonaliBedade** [comment]
What content and features are required on the about page? @sruti2024

**Comment by sonaliBedade** [comment]
@sruti2024 here's a link to the recording of the changes I made...any suggestions?

https://user-images.githubusercontent.com/71630760/115597170-9b887d00-a2f6-11eb-9932-48c8eb6c0a90.mp4
