### ISSUE TITLE
Update README.md file

### ISSUE THREAD

**Issue by aditi1403** [sruti2024/PRO_Act#80]
I have made some grammatical edits to the README.md file. Kindly refer to PR #79.

**Comment by akshaypk123** [comment]
I am a gsscoc 21 participant, I am a total newbie so please assign me this issue, so as to start with the projects

**Comment by sakshamgurbhele** [comment]
Can I on this issue?

**Comment by darpankhanna** [comment]
please assign me this issue @SaiSudhaV
