### ISSUE TITLE
Change password functionality

### ISSUE THREAD

**Issue by somya51p** [sruti2024/PRO_Act#82]
### **Feature request**:
I wish to add functionality to change the password of their own profiles.

### **Is your feature request related to a problem? Please describe. (optional)**:
Users once logged in, don't have the option to change their password. So wish to add the change password option.

### **Describe the solution you'd like**:
Just wish to add a button on the profile page if the user wishes to change one's password.

### **Describe how this feature will be useful to our readers**:
This is an additional functionality as users like changing their passwords after a certain time due to security issues.

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. 
Checked, It has not been assigned.

@PROTechThor @SaiSudhaV @sruti2024 Please assign me this issue. I wish to contribute to it under GSSOC'21.

**Comment by sruti2024** [comment]
Go one , nice issue indeed!!
