### ISSUE TITLE
[BUG] [GSSOC' 21] Footer overlapping techstack

### ISSUE THREAD

**Issue by Aditya201551** [sruti2024/PRO_Act#88]
@sruti2024 @chdharm @SaiSudhaV @PROTechThor 

### **Describe the bug:**
- Footer is overlapping the options of tech stack in `add_project page`

### **To Reproduce:**
Steps to reproduce the behaviour:
- Run the project locally before merging the fixes

### **Expected behavior:**
- I expected that the tech stack menu would float over the footer but the footer is overlapping the tech stack menue

### **Screenshots:**
![Screenshot (54)](https://user-images.githubusercontent.com/32588231/112512159-20947b00-8db9-11eb-9b49-564c2d398b28.png)

### **Additional context:**
NA

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by SaiSudhaV** [comment]
Good issue @Aditya201551 Go ahead resolving it.
