### ISSUE TITLE
Create a SignUp page

### ISSUE THREAD

**Issue by sruti2024** [sruti2024/PRO_Act#9]
Create a sign up page with general criteria like first name last name ,Email ID , Contact Number, Password and confirm password.
Use the same CSS as that of Login page, and link this page to the create account written on the login page.

**Comment by saaiswetha** [comment]
I would like to contribute to this issue, am a part of GSSoC'21.

**Comment by sruti2024** [comment]
Will assign once the coding phase starts !

**Comment by rohank2502** [comment]
I will like to work on this issue

**Comment by Praneeth-rdy** [comment]
Hey, I am interested in contributing to this. I will start designing the prototype on Figma immediately after you assign the issue to me. I will share the initial design here and after the confirmation of design, I can start working on the development part.

**Comment by kalpanapurohit** [comment]
I would like to work on this issue as a GSSOC'21 participant.

**Comment by PROTechThor** [comment]
@Praneeth-rdy 

> 
Hey, I am interested in contributing to this. I will start designing the prototype on Figma immediately after you assign the issue to me. I will share the initial design here and after the confirmation of design, I can start working on the development part.

About this, it looks like we already have a login page, and this sign-up page should use the same CSS. I don't think a Figma mockup is necessary. You can save time by jumping straight into coding. @sruti2024 Can you please clarify the requirements here? 

Also, @Praneeth-rdy @kalpanapurohit @saumyaparikh Sorry, but it looks like you guys are too late. @saaiswetha was here first, and they should be assigned. Can you guys please find another issue to work on? If all the issues are already claimed? You may even create your own issue and request to be assigned! If you think there's any cool thing that can be added to PRO_Act, create an issue for it :)

Thank you all for your interest :D

**Comment by Naman-12911** [comment]
Hello, sir I can easily solve this issue please assign me this issue.
Under GSSOC.

**Comment by SwarupKharul** [comment]
Hey, I am a GSSoc participant. I would like to solve this issue. Can you please assign it to me!

**Comment by sruti2024** [comment]
@PROTechThor completely agreed , I am assigning this one to @saaiswetha as she was the first one in the lot , rest all ur ideas are also cool @ashutoshkrris your otp verification part also seems to be something that can be implemented as a forgot password , so if you wish u can frame your own issue and that will be assigned to you , 
for the rest @Praneeth-rdy  @kalpanapurohit @saumyaparikh @Naman-12911 @SwarupKharul frame issues of your own they shall be assigned to you!

**Comment by saaiswetha** [comment]
@sruti2024 should the sign up page also have backend implementation? Or just frontend is enough?

**Comment by ashutoshkrris** [comment]
> @sruti2024 should the sign up page also have backend implementation? Or just frontend is enough?

I feel, there must be backend implementation as well. Password Validations, Email Validations, Email Verifications should be there to avoid fake users signing up

**Comment by sruti2024** [comment]
@saaiswetha yes backend is also required , if you have any more doubts please ask it on discord it is easier to respond on time

**Comment by sruti2024** [comment]
@ashutoshkrris assigning you with this issue since the previous assignee seems to be inactive , hope u complete the task on time!

**Comment by ashutoshkrris** [comment]
Sure @sruti2024 
I'll work on it and keep updating you.

**Comment by ashutoshkrris** [comment]
Hi @sruti2024 
I've worked on the signup page.
I've used ajax validations and otp verification.
Demo video is attached below :

https://user-images.githubusercontent.com/47353498/112758724-76616100-900d-11eb-9156-bace67ed7aec.mp4
