### ISSUE TITLE
[Gssoc'21] Website is not Responsive 

### ISSUE THREAD

**Issue by arpit456jain** [sruti2024/PRO_Act#92]
### **Describe the bug:**
The website is not responsive in small screen like phones wrong use of bootstrap classes,
hard-coded CSS in some places.
Please Take  a Look in Video.

https://user-images.githubusercontent.com/55352601/112650489-70367d80-8e71-11eb-8b68-ff36319c1189.mp4

### **To Reproduce:**
4. See an error

### **Expected behavior:**
It should be fully responsive as it is made in bootstrap.

### **Additional context:**

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.
**I am a Gssoc'21 participant. Kindly assign it to me.**

**Comment by arpit456jain** [comment]
@PROTechThor please assign me this issue as i am a GSSoC'21 participant.

**Comment by sruti2024** [comment]
Go on with it!!

**Comment by arpit456jain** [comment]
@sruti2024 Kindly assign this to me and please add labels of gsscoc'21 as i am a Gssoc'21 participant.

**Comment by arpit456jain** [comment]
@sruti2024 mam can I move CSS in contact page between body to head tag. by making a separate block
CSS should be always in head tag.

**Comment by arpit456jain** [comment]
@sruti2024 please Review My PR
