### ISSUE TITLE
Adding a Favicon logo on the website title in browser tab

### ISSUE THREAD

**Issue by VaibhavSharma24** [sruti2024/PRO_Act#94]
**Feature request**

i want to add a fevicon logo on this website i am a gssoc participant and would love to work on this project.

**Comment by sruti2024** [comment]
sure go on !

**Comment by VaibhavSharma24** [comment]
thanks, okay i am on it.

**Comment by Ananyaagupta** [comment]
I would like to work on the issue I am a designer and have designed various favicons before. i would like to collaborate if possible

**Comment by sruti2024** [comment]
@VaibhavSharma24 updates?

**Comment by VaibhavSharma24** [comment]
> @VaibhavSharma24 updates?

@sruti2024 Sorry for not updating you i was busy in my college yeah i have made some designs i am sharing them and tell me how they are or if anything i need to change

**Comment by VaibhavSharma24** [comment]
![fevicon 1](https://user-images.githubusercontent.com/72144747/113513287-a1f0c800-9586-11eb-9439-f529c3564913.png)
![fevicon 2](https://user-images.githubusercontent.com/72144747/113513297-a917d600-9586-11eb-9563-9000c55aaed3.png)

**Comment by VaibhavSharma24** [comment]
@Ananyaagupta  yeah i am okay with that we can then select whichever look good.
