### ISSUE TITLE
Enhancing the CSS of profile page

### ISSUE THREAD

**Issue by somya51p** [sruti2024/PRO_Act#96]
### **Feature request**:
Enhancing the CSS of the profile page by giving good hover effects to the buttons and also arranging the alignment of the page.

### **Describe the solution you'd like**:
Giving good hover effects to the buttons, suitable font, and also arranging the alignment of the page.

### **Describe how this feature will be useful to our readers**:
This would make the page more attractive.

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. 

@sruti2024 Please assign me this issue. I wish to contribute to it under GSSOC'21

**Comment by sruti2024** [comment]
could you please elaborate on the changes you would like to make

**Comment by somya51p** [comment]
@sruti2024 the hover effects of buttons are primary blue, not matching with the theme of the project. the alignment of the details is looking attractive enough. Just wish to make the page look attractive. 

![1](https://user-images.githubusercontent.com/64978837/113248209-5500af00-9271-11eb-8375-c707f974293f.PNG)

**Comment by sruti2024** [comment]
okay make a design and get it confirmed will give the level tag based on the quality of design !

**Comment by somya51p** [comment]
@sruti2024 Made two designs, review them, suggest the changes if any, and finalize. ThankYou!

![2](https://user-images.githubusercontent.com/64978837/113833514-65e87d80-97a7-11eb-9e92-a81dfd722a13.PNG)

![4](https://user-images.githubusercontent.com/64978837/113833546-6d0f8b80-97a7-11eb-91ad-3dd9f4849930.PNG)

**Comment by somya51p** [comment]
@SaiSudhaV @sruti2024 Please review the above designs. and I would code the better one

**Comment by somya51p** [comment]
@sruti2024 @SaiSudhaV Please review the designs.

**Comment by sruti2024** [comment]
yup the design is cool go ahead !!
